"""
Copilot:
Create an Excel spreadsheet. 
List all the countries of the world in the first column and their capitals in the second column.

"""
from openpyxl import Workbook

# Create a new workbook and sheet
wb = Workbook()
sheet = wb.active
sheet.title = "Countries & Capitals"

# Add headers
sheet.append(["Country", "Capital"])

# List of countries and their capitals (abbreviated for example)
countries_capitals = [
    ["Afghanistan", "Kabul"],
    ["Albania", "Tirana"],
    ["Algeria", "Algiers"],
    ["Andorra", "Andorra la Vella"],
    ["Angola", "Luanda"],
    ["Argentina", "Buenos Aires"],
    ["Armenia", "Yerevan"],
    ["Australia", "Canberra"],
    ["Austria", "Vienna"],
    ["Azerbaijan", "Baku"],
    ["Bahamas", "Nassau"],
    ["Bahrain", "Manama"],
    ["Bangladesh", "Dhaka"],
    ["Barbados", "Bridgetown"],
    ["Belarus", "Minsk"],
    ["Belgium", "Brussels"],
    ["Belize", "Belmopan"],
    ["Benin", "Porto-Novo"],
    ["Bhutan", "Thimphu"],
    ["Bolivia", "Sucre (constitutional), La Paz (administrative)"],
    ["Bosnia and Herzegovina", "Sarajevo"],
    ["Botswana", "Gaborone"],
    ["Brazil", "Brasilia"],
    ["Brunei", "Bandar Seri Begawan"],
    ["Bulgaria", "Sofia"],
    ["Burkina Faso", "Ouagadougou"],
    ["Burundi", "Gitega"],
    ["Cambodia", "Phnom Penh"],
    ["Cameroon", "Yaoundé"],
    ["Canada", "Ottawa"],
    ["Cape Verde", "Praia"],
    ["Central African Republic", "Bangui"],
    ["Chad", "N'Djamena"],
    ["Chile", "Santiago"],
    ["China", "Beijing"],
    ["Colombia", "Bogotá"],
    ["Comoros", "Moroni"],
    ["Congo (Democratic Republic)", "Kinshasa"],
    ["Congo (Republic)", "Brazzaville"],
    ["Costa Rica", "San José"],
    ["Croatia", "Zagreb"],
    ["Cuba", "Havana"],
    ["Cyprus", "Nicosia"],
    ["Czech Republic", "Prague"],
    ["Denmark", "Copenhagen"],
    ["Djibouti", "Djibouti"],
    ["Dominica", "Roseau"],
    ["Dominican Republic", "Santo Domingo"],
    ["Ecuador", "Quito"],
    ["Egypt", "Cairo"],
    ["El Salvador", "San Salvador"],
    ["Equatorial Guinea", "Malabo"],
    ["Eritrea", "Asmara"],
    ["Estonia", "Tallinn"],
    ["Eswatini", "Mbabane"],
    ["Ethiopia", "Addis Ababa"],
    ["Fiji", "Suva"],
    ["Finland", "Helsinki"],
    ["France", "Paris"],
    ["Gabon", "Libreville"],
    ["Gambia", "Banjul"],
    ["Georgia", "Tbilisi"],
    ["Germany", "Berlin"],
    ["Ghana", "Accra"],
    ["Greece", "Athens"],
    ["Grenada", "St. George's"],
    ["Guatemala", "Guatemala City"],
    ["Guinea", "Conakry"],
    ["Guinea-Bissau", "Bissau"],
    ["Guyana", "Georgetown"],
    ["Haiti", "Port-au-Prince"],
    ["Honduras", "Tegucigalpa"],
    ["Hungary", "Budapest"],
    ["Iceland", "Reykjavik"],
    ["India", "New Delhi"],
    ["Indonesia", "Jakarta"],
    ["Iran", "Tehran"],
    ["Iraq", "Baghdad"],
    ["Ireland", "Dublin"],
    ["Israel", "Jerusalem"],
    ["Italy", "Rome"],
    ["Jamaica", "Kingston"],
    ["Japan", "Tokyo"],
    ["Jordan", "Amman"],
    ["Kazakhstan", "Nur-Sultan"],
    ["Kenya", "Nairobi"],
    ["Kiribati", "Tarawa"],
    ["Kuwait", "Kuwait City"],
    ["Kyrgyzstan", "Bishkek"],
    ["Laos", "Vientiane"],
    ["Latvia", "Riga"],
    ["Lebanon", "Beirut"],
    ["Lesotho", "Maseru"],
    ["Liberia", "Monrovia"],
    ["Libya", "Tripoli"],
    ["Liechtenstein", "Vaduz"],
    ["Lithuania", "Vilnius"],
    ["Luxembourg", "Luxembourg City"],
    ["Madagascar", "Antananarivo"],
    ["Malawi", "Lilongwe"],
    ["Malaysia", "Kuala Lumpur"],
    ["Maldives", "Malé"],
    ["Mali", "Bamako"],
    ["Malta", "Valletta"],
    ["Mauritania", "Nouakchott"],
    ["Mauritius", "Port Louis"],
    ["Mexico", "Mexico City"],
    ["Moldova", "Chisinau"],
    ["Monaco", "Monaco"],
    ["Mongolia", "Ulaanbaatar"],
    ["Montenegro", "Podgorica"],
    ["Morocco", "Rabat"],
    ["Mozambique", "Maputo"],
    ["Myanmar", "Naypyidaw"],
    ["Namibia", "Windhoek"],
    ["Nauru", "Yaren"],
    ["Nepal", "Kathmandu"],
    ["Netherlands", "Amsterdam"],
    ["New Zealand", "Wellington"],
    ["Nicaragua", "Managua"],
    ["Niger", "Niamey"],
    ["Nigeria", "Abuja"],
    ["North Macedonia", "Skopje"],
    ["Norway", "Oslo"],
    ["Oman", "Muscat"],
    ["Pakistan", "Islamabad"],
    ["Palau", "Ngerulmud"],
    ["Panama", "Panama City"],
    ["Papua New Guinea", "Port Moresby"],
    ["Paraguay", "Asunción"],
    ["Peru", "Lima"],
    ["Philippines", "Manila"],
]

# Add all countries to the Excel sheet
for country, capital in countries_capitals:
    sheet.append([country, capital])

# Save the workbook
wb.save("Countries_and_Capitals.xlsx")
print("Excel file created successfully!")