#13_polynomgenerator.py
from sympy import *
x,a,b,c=symbols('x,a,b,c')
x1,x2=-6,4
d=-4
f=a*x**3+b*x**2+c*x+d
df1=diff(f,x,1)
df2=diff(f,x,2)
#Gleichungen
g1=f.subs(x,2)
g2=df1.subs(x,-2)
g3=df2.subs(x,0)
i=0
L=solve((g1,g2,g3),a,b,c,dict=True)
fx=f.subs({a:L[i][a],b:L[i][b],c:L[i][c]})
#Ausgabe
print("Lösungsmenge:\n",L)
print("a=",L[i][a])
print("b=",L[i][b])
print("c=",L[i][c])
print("f(x)=",fx)
#Darstellung
p=plot(fx,(x,x1,x2),show=False,visible=False,ylim=(-10,5))
p.show()

'''
p.save("/Users/veit/documents/Python_Mathe/Export_Mathe_Python_neu/Abbildungen/09_010.pdf")
p.save("/Users/veit/documents/Python_Mathe/Export_Mathe_Python_neu/Abbildungen/09_010.svg")
'''
